language: python
python:
- '2.7'

before_install:
- openssl aes-256-cbc -K $encrypted_b52943e120ac_key -iv $encrypted_b52943e120ac_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"  
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

script:
- export LANG=en_US.UTF-8
- pip install -r requirements.txt
- pip install psycopg2-binary
- runestone build --all

notifications:
  slack:
    secure: OfeZ/+YHpSl7GNFkzEKu0uObuMdymKmDEeDyfB++RaglalcgkDQAqrCPx+YVw6brXOHGeC6BkGJe/Fs143Ai8/yf38nMmZg/dej5nLgZNST67jWaapIydx5QeuCrsRKvUP+z6yEYoBkYXTsYPyTiKGGsyzvX6dimZRT4nD8qrv0=

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh

